<?php include VIEW . 'header.phtml' ?>

<?php include VIEW . 'car/navcars.phtml' ?>


<h1>Show Car List</h1>
<?php 

	if (array_key_exists('cars', $this->view_data)) {
		$table = '<table border=1>';
		foreach ($this->view_data['cars'] as $car) {
			$car_info = explode(',', $car);
			$table .= '<tr>';
			foreach ($car_info as $item) {
				$table .= '<td>' . $item . '</td>';
			}
			$table .= '</tr>';
		}
		$table .= '</table>';

		echo $table;
	}

 ?>

<?php include VIEW . 'footer.phtml' ?>